#!/bin/sh
#
# Avoid Dnsmasq to answer DHCP request on multipath interfaces with direct modems gateways
# Create the Dnsmasq options to choose Gateway in DHCP config
#

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0

. /lib/functions.sh

config_load network
config_get mode $INTERFACE multipath

case "$mode" in
  "off")
        exit 0;;
  "master")
        mode="on";;
  "on");;
  "backup");;
  "handover");;
  *)
	exit 1;;
esac

checktag() {
        [ "$1" == "$INTERFACE" ] && {
                TAGFOUND="$INTERFACE"
        }
}

checkdhcpignore() {
        local itf
        local ignore

        config_get itf $1 interface
        [ "$itf" == "$INTERFACE" ] && {
                config_get_bool ignore $1 ignore
                [ "$ignore" == "1" ] && {
                        IGNOREFOUND="$1"
                }
        }
}

config_load dhcp
config_foreach checktag tag
config_foreach checkdhcpignore dhcp

if [ -n "$IGNOREFOUND" ]; then
	uci del dhcp.$IGNOREFOUND
fi
# Create static dhcp range
uci set dhcp.$INTERFACE=dhcp
uci set dhcp.$INTERFACE.dynamicdhcp=0
uci set dhcp.$INTERFACE.interface=$INTERFACE
uci set dhcp.$INTERFACE.start=0

uci commit
