#!/bin/sh
#
# Clean udp conntrack when tun0 or xtun0 change state
#
[ "$INTERFACE" = tun0 -o "$INTERFACE" = xtun0 ] || exit 0

clearConntrack() {
	local mode
	config_get mode $1 multipath
	case "$mode" in
		"off")
			return;;
		"master")
			mode="on";;
		"on");;
		"backup");;
		"handover");;
		*)
			return;;
	esac

	network_get_ipaddr if_ipaddr $1
	if [ -n "$if_ipaddr" ]; then
		/usr/sbin/conntrack -p udp -q $if_ipaddr -D 1>/dev/null
	fi
}

if [ "$ACTION" = ifup -o "$ACTION" = ifupdate ]; then
	. /lib/functions.sh
	. /lib/functions/network.sh

	config_load network
	config_foreach clearConntrack interface
elif [ "$ACTION" = ifdown ]; then
	. /lib/functions.sh
	. /lib/functions/network.sh

	network_get_ipaddr if_ipaddr $INTERFACE
	if [ -n "$if_ipaddr" ]; then
		/usr/sbin/conntrack -p udp -q $if_ipaddr -D 1>/dev/null
	fi
fi

