#!/bin/sh
# shellcheck disable=SC1091
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

# shellcheck disable=SC2016
details=$(jq -n -c --arg interface "$INTERFACE" --arg device "$DEVICE" \
	'{ interface: $interface, device: $device }')

otb_save_event "$ACTION" "$details"
