#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC1091
set -e

. /lib/functions.sh
. /lib/functions/network.sh

check_interface() {
	device=
	output=
	gateway=
	config_get device "$1" device
	network_get_gateway gateway "$1" || true
	if [ -z "$gateway" ]; then
		return 0
	fi
	output=$(set -x; curl -sS --max-time 1 --interface "$device" http://multipath-tcp.org 2>&1)
	printf "[%s] \t : %s\n" "$device" "$output"
}

# Load the network config
config_load network
# For each interface, run check_interface
config_foreach check_interface interface
