#!/bin/sh /etc/rc.common

START=60

# Generate dscp tagging preferences
IPT="/usr/sbin/iptables -t mangle -w"
genrateDscp() {
	local ipset proto src_ip src_port dest_ip $ipset dest_port class

	config_get proto $1 proto all
	config_get ipset $1 ipset
	config_get src_ip $1 src_ip 0.0.0.0/0
	config_get src_port $1 src_port 0:65535
	config_get dest_ip $1 dest_ip 0.0.0.0/0
	config_get dest_port $1 dest_port 0:65535
	config_get class $1 class
	config_get direction $1 direction "upload"

	# Take OTB point of view when using both direction (inverse source and destination)
	if [ "$direction" == "both" ]; then
		config_get src_ip $1 dest_ip 0.0.0.0/0
		config_get src_port $1 dest_port 0:65535
		config_get dest_ip $1 src_ip 0.0.0.0/0
		config_get dest_port $1 src_port 0:65535
	fi

	if [ "$direction" == "upload" -o "$direction" == "both" ]; then
		case $proto in
			tcp)
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j RETURN 2>/dev/null
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class 2>/dev/null
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j RETURN
			;;
		udp)
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j RETURN 2>/dev/null
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class 2>/dev/null
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m multiport --sports $src_port -m multiport --dports $dest_port -m comment --comment "dscp_$1" -j RETURN
			;;
		*)
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m comment --comment "dscp_$1" -j RETURN 2>/dev/null
				$IPT -D dscp -p $proto -s $src_ip -d $dest_ip $ipset -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class 2>/dev/null
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m comment --comment "dscp_$1" -j DSCP --set-dscp-class $class
				$IPT -A dscp -p $proto -s $src_ip -d $dest_ip $ipset -m comment --comment "dscp_$1" -j RETURN
			;;
		esac
	fi
}

reload()
{
        $IPT -F dscp 2>/dev/null
        config_load dscp
        config_foreach genrateDscp classify
        /usr/bin/pkill -USR2 -f "mwan3track -i tun0"
}

restart()
{
        reload
}

start()
{
	# Clear DSCP rules before recreate
	$IPT -F dscp 2>/dev/null
	$IPT -N dscp 2>/dev/null
	config_load dscp
	config_foreach genrateDscp classify
	$IPT -D PREROUTING -j dscp 2>/dev/null
	$IPT -A PREROUTING -j dscp
	/usr/bin/pkill -USR2 -f "mwan3track -i tun0"
}

stop()
{
        # Clear DSCP rules before recreate
        $IPT -F dscp 2>/dev/null
        $IPT -N dscp 2>/dev/null
}
