#!/bin/sh /etc/rc.common
# shellcheck disable=SC2154,SC2034,SC1091

START=95
STOP=10

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/otb-lte-watchdog
	procd_set_param respawn 0 60 2
	procd_set_param term_timeout 600
	procd_set_param stderr 1
	procd_close_instance
}
