#!/bin/sh /etc/rc.common
# shellcheck disable=SC2154,SC2034,SC1091

START=90
STOP=10

USE_PROCD=1

boot() {
    . /lib/overthebox
    otb_save_event boot
    start "$@"
}

start_service() {
	procd_open_instance
	procd_set_param command /bin/otb-daemon
	procd_set_param respawn 0 5 0
	procd_set_param term_timeout 600
	procd_set_param stderr 1
	procd_close_instance
}
