#!/bin/sh /etc/rc.common
START=60

start()
{
        /usr/bin/pkill -USR2 -f "mwan3track -i tun0"
}

reload()
{
        start
}

restart()
{
        start
}

stop()
{
	/etc/init.d/dscp stop
	/usr/lib/qos/run.sh stop
	curl -s --connect-timeout 5 -X DELETE api/qos
}
