#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

START=60

reload()
{
	# Ask tun0 to load QoS
	/usr/bin/pkill -USR2 -f "mwan3track -i tun0"
}

start()
{
	reload
}

restart()
{
	reload
}

stop()
{
	/etc/init.d/dscp stop
	/usr/lib/qos/run.sh stop
	curl -s --max-time 5 -X DELETE api/qos
}
