#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "network"
	procd_add_raw_trigger "interface.*" 1000 /etc/init.d/update_confmwan reload
}

reload_service()
{
	/usr/bin/otb_update_confmwan
}

boot()
{
	reload_service
}
