sudo: required
dist: trusty
language: c
compiler: gcc
addons:
  apt:
    packages:
    - libxml-parser-perl
script:
- ./build-packages.sh
- find sdk -name '*.ipk' -execdir curl -T {} https://transfer.sh/{} \; -exec echo \;
deploy:
  provider: releases
  api_key:
    secure: a6CHuVNn00FAN48qdw2gcAVop/5WtZXa8vBO2RB4cLm9dkMF6UzpIGiFhIWE6tidu73kf4ZN9pfUWIXDONj5rYy5fSvYMkAxBgF8R1SCz03pAetLht5MHnnV0xXw1sVEswitx2XWd95OJah2AV6z5JuLOgaiQL38wD7iAGkDiHvAmOqE645keqBgCsrEjoL8d3/sThGt/zCH7Vbn/apnWcqeUZg8yTPVRR7HCL56PFpWo5b9q+b+ZV/zwu7xokwVnk84QDWL5hYJvv2n7b57d5LKma/fuwn/HVomtqNjbIadn5tWYeEFmf7knXpHKX1crrr/nZB+sp7lzMc8kI8QUz45Ev6vVXzkaCfsm6qGRZsveF2UqsH+z4t8ca4mM6KRaokcp4iFMSekP5VToUk/sLJhzCPF0uyQWHYMI/kAmK1GEB7py60bQVg6Nf1OA8RNBkHZcAVAI46Ff0yeasPw8d5hRJlb5BZFY9ZbK96PSCNKe/Oeih+H3mUW1Xpr7yRPW8teQfF4xtPyNttjqt86PfA7u0dNrsIGqyGLu9xQK0x3JcskPA6iEnaDDgOWe/+HklXjxJKJeBDpWyzAej5SOZx6G7hjQcufy/a+smaAFFlai9SxKErHWPGdyxByTFAnKL406XHl1beLAOklQAqOpV1t21ZMis/624kuNrXTn9U=
  skip_cleanup: true
  file_glob: true
  file: sdk/bin/x86-glibc/packages/base/*
  on:
    all_branches: true
    tags: true
