#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh
. /lib/functions/network.sh

_gt_setup_interface() {
	local ipaddr=
	network_get_ipaddr ipaddr "$1"

	local multipath=
	config_get multipath "$1" multipath "off"

	case "$multipath" in
		on)     glorytun path "$ipaddr" up ;;
		backup) glorytun path "$ipaddr" backup ;;
		off)    glorytun path "$ipaddr" down ;;
	esac
}

config_load network
config_foreach _gt_setup_interface interface
