#!/bin/sh
# shellcheck disable=SC1091,SC1090,SC2034
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

while true; do
	glorytun path dev tun0 2>/dev/null | \
		while read -r _ _ _ IP _ PUBIP _; do
			[ "$PUBIP" ] || continue
			[ "$PUBIP" = "-" ] && continue
			PUBIP_OLD=$(otb_get_data "$IP/pubip")
			[ "$PUBIP" = "$PUBIP_OLD" ] && continue
			otb_set_data "$IP/pubip" "$PUBIP"
			asn="$(curl --max-time 2 --silent --show-error "api.iptoasn.com/v1/as/ip/$PUBIP")"
			[ "$asn" ] && otb_set_data "$IP/asn" "$asn"
		done

	if glorytun sync dev tun0 2>/dev/null; then
		ubus -S call network.interface.tun0 up
	else
		ubus -S call network.interface.tun0 down
	fi

	sleep 5
done
