#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

START=90
STOP=10

USE_PROCD=1

_validate_section() {
	uci_validate_section otb-tracker "$1" "$2" \
		'call:string' \
		'host:host' \
		'timeout:uinteger' \
		'tries:uinteger' \
		'interval:uinteger' \
		'options:string'
	[ -n "$call" ] && OTB_TRACKER_CALL="$call"
	[ -n "$host" ] && OTB_TRACKER_HOST="$host"
	[ -n "$tries" ] && OTB_TRACKER_TRIES="$tries"
	[ -n "$timeout" ] && OTB_TRACKER_TIMEOUT="$timeout"
	[ -n "$options" ] && OTB_TRACKER_OPTIONS="$options"
	[ -n "$interval" ] && OTB_TRACKER_INTERVAL="$interval"
}

_add_dscp_chain() {
	iptables -w -t mangle -N tracker_dscp
	iptables -w -t mangle -I OUTPUT -j tracker_dscp
}

_add_dscp_rule() {
	iptables -w -t mangle -A tracker_dscp \
		-p udp --dport 53 \
		-j DSCP --set-dscp-class cs7 \
		-m comment --comment "DNS queries"
}

_remove_dscp_chain() {
	iptables -w -t mangle -F tracker_dscp 2>/dev/null || return
	iptables -w -t mangle -D OUTPUT -j tracker_dscp
	iptables -w -t mangle -X tracker_dscp
}

_launch_tracker() {
	case "$1" in
		loopback|lan*|if0*) return;;
	esac
	config_get interface_type "$1" type
	_validate_section "defaults" "defaults"
	_validate_section "rule_type" "$interface_type"
	_validate_section "interface" "$1"
	procd_open_instance
	# shellcheck disable=SC2086
	procd_set_param command /bin/otb-tracker "$1" "$OTB_TRACKER_CALL" $OTB_TRACKER_OPTIONS
	procd_append_param env \
		"OTB_TRACKER_HOST=$OTB_TRACKER_HOST" \
		"OTB_TRACKER_TIMEOUT=$OTB_TRACKER_TIMEOUT" \
		"OTB_TRACKER_TRIES=$OTB_TRACKER_TRIES" \
		"OTB_TRACKER_INTERVAL=$OTB_TRACKER_INTERVAL"
	procd_set_param respawn 0 10 0
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	_add_dscp_chain
	# We should add the rules based on the tracker used
	_add_dscp_rule

	config_load network
	config_foreach _launch_tracker interface
}

stop_service() {
	_remove_dscp_chain
}

service_triggers() {
	procd_add_reload_trigger otb-tracker network
}

reload_service() {
	stop
	start
}
