#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
{
	START=90
	STOP=10
	USE_PROCD=1
}

start_service() {
	procd_open_instance
	procd_set_param command /bin/otb-tracker
	procd_set_param respawn 0 10 0
	procd_set_param stderr 1
	procd_close_instance
}
