#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

. /lib/functions.sh
. /lib/overthebox

config_load network

_log() {
	logger -t otb-qos "$@"
}

_setup_interface() {
	# The QoS should be applied only if traffic control is set to static
	local trafficcontrol
	config_get trafficcontrol "$1" trafficcontrol
	[ "$trafficcontrol" = static ] || return 0

	local ifname upload
	config_get ifname "$1" ifname
	config_get upload "$1" upload

	_log "setting upload QoS on $ifname [$1] to ${upload}kbps"
	tc qdisc rep dev "$ifname" root cake bandwidth "$upload"kbit diffserv4 flows memlimit 10m
}

_stop_interface() {
	local ifname
	config_get ifname "$1" ifname

	if tc qdisc del dev "$ifname" root cake 2>/dev/null; then
		_log "upload QoS deleted on $ifname [$1]"
	fi
}

_start() {
	_log "starting QoS"
	config_foreach _setup_interface interface
}

_stop() {
	_log "stopping QoS"
	config_foreach _stop_interface interface
}

case "$1" in
	start) _start ;;
	setup) _setup_interface "$2" ;;
	stop) _stop ;;
	*) exit 1 ;;
esac
