#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
START=90
# shellcheck disable=SC2034
STOP=10
# shellcheck disable=SC2034
USE_PROCD=1

start_service() {
	# Always stop the QoS before starting it
	otb-qos stop
	otb-qos start
}

stop_service() {
	otb-qos stop
}

reload_service() {
	start
}

service_triggers() {
	procd_add_reload_trigger network
}
