#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

# Migration from 0.8.x to 0.9.x
_replace_ifname_to_device() {
	
	ifname=
	ifname="$(uci -q get network."$1".ifname)"

	[ -z "$ifname" ] && return

	if [ "$1" = "lan" ]; then
		uci -q batch <<-EOF
			delete network.$1.ifname
			delete network.$1.type
			set network.$1.device='br-$1'
			add network device
			set network.@device[-1].name='br-$1'
			set network.@device[-1].type='bridge'
			add_list network.@device[-1].ports="$ifname"
		EOF
	else
		uci -q batch <<-EOF
			delete network.$1.ifname
			set network.$1.device=$ifname
		EOF
	fi
	
}

config_load network
config_foreach _replace_ifname_to_device interface