#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

_setup() {
	local name network
	config_get name "$1" name
	config_get network "$1" network

	case "$name" in
	lan|wan)
		for iface in $network; do
			[ "$(uci -q get "network.$iface")" ] || \
				uci -q del_list "firewall.$1.network=$iface"
		done
		uci -q rename "firewall.$1=$name"
		;;
	esac
}

config_load firewall
config_foreach _setup zone

uci -q batch <<-EOF
set firewall.allow_dhcp_request=rule
set firewall.allow_dhcp_request.name=Allow-DHCP-Request
set firewall.allow_dhcp_request.src=wan
set firewall.allow_dhcp_request.proto=udp
set firewall.allow_dhcp_request.dest_port=67
set firewall.allow_dhcp_request.target=ACCEPT
set firewall.allow_dhcp_request.family=ipv4

del_list firewall.wan.masq_dest='!10.0.0.0/8'
del_list firewall.wan.masq_dest='!172.16.0.0/12'
del_list firewall.wan.masq_dest='!192.168.0.0/16'
del_list firewall.wan.masq_src='!151.127.0.0/16'
del_list firewall.wan.masq_src='!109.190.0.0/16'

add_list firewall.wan.masq_dest='!10.0.0.0/8'
add_list firewall.wan.masq_dest='!172.16.0.0/12'
add_list firewall.wan.masq_dest='!192.168.0.0/16'
add_list firewall.wan.masq_src='!151.127.0.0/16'
add_list firewall.wan.masq_src='!109.190.0.0/16'
EOF
