#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

_setup() {
	name=
	config_get name "$1" name

	case "$name" in
	mptcp|lan|wan)
		uci -q rename "firewall.$1=$name"
		;;
	esac
}

config_load firewall
config_foreach _setup zone

uci -q batch <<-EOF
set firewall.allow_dhcp_request=rule
set firewall.allow_dhcp_request.name=Allow-DHCP-Request
set firewall.allow_dhcp_request.src=wan
set firewall.allow_dhcp_request.proto=udp
set firewall.allow_dhcp_request.dest_port=67
set firewall.allow_dhcp_request.target=ACCEPT
set firewall.allow_dhcp_request.family=ipv4
EOF

exit 0
