#!/bin/sh
# shellcheck disable=SC1091
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# Check if LTE interface already exists
if [ -z "$(uci get network.lte)" ]; then
	uci -q batch <<-EOF
		set network.lte=interface
		set network.lte.proto='modemmanager'
		set network.lte.multipath='on'
		set network.lte.device='/sys/devices/pci0000:00/0000:00:14.0/usb2/2-2'
		set network.lte.auth='none'
		set network.lte.iptype='ipv4'
		set network.lte.loglevel='ERR'
		set network.lte.ip4table=205
		set network.lte.metric=35

		del_list firewall.wan.network="lte"
		add_list firewall.wan.network="lte"
	EOF
fi
