#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC1091
. /lib/functions.sh

multipath=
multipath_status=0
config_load network
config_get multipath globals multipath
[ "$multipath" = "enable" ] && multipath_status=1

# Global MPTCP configuration
sysctl -qw net.mptcp.enabled="$multipath_status"
ip mptcp endpoint flush
[ "$multipath_status" = "0" ] && {
	ip mptcp limits set add_addr_accepted 0 subflows 0
	exit 0
}

# Set mptcp limits to max
ip mptcp limits set add_addr_accepted 8 subflows 8

# Configuration by interface
_setup_interface() {
	device=
	config_get device "$1" device
	[ -z "$device" ] && return 0

	if_multipath=
	config_get if_multipath "$1" multipath "off"
	
	# MPTCP is already flushed so return
	[ "$if_multipath" = "off" ] && return 0

	# Get ipv4 address of the interface 
	ipv4=$(ifstatus "$1" | jq '.["ipv4-address"][0]["address"]' | sed 's/"//g')
	# Check if interface is down
	[ "$ipv4" = "null" ] && return 0

	# shellcheck disable=SC2086
	case $if_multipath in
		master|on) ip mptcp endpoint add $ipv4 dev $device subflow signal;; 
		backup) ip mptcp endpoint add $ipv4 dev $device backup;;
	esac
}

config_foreach _setup_interface interface
