#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

#
# Enable or disable Multipath
#
enable=$(uci -q get network.globals.multipath)
if [ "$enable" = "disable" ]; then
	sysctl -qw net.mptcp.mptcp_enabled=0
elif [ "$enable" = "enable" ]; then
	sysctl -qw net.mptcp.mptcp_enabled=1
else
	exit 0
fi
