#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Administration - full-featured for full control
LUCI_DEPENDS:=+luci-base +libubus-lua

PKG_BUILD_DEPENDS:=iwinfo

PKG_VERSION:=v1.0
PKG_RELEASE:=1

include ../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

