#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

validate_section() {
	uci_validate_section mwan3 interface "$1" \
		'enabled:bool:1' \
		'track_ip:list(host)' \
		'track_method:string:dns' \
		'reliability:uinteger:1' \
		'count:uinteger:1' \
		'timeout:uinteger:3' \
		'interval:uinteger:5' \
		'down:uinteger:3' \
		'up:uinteger:6'
}

start_instance() {
	validate_section "$1" || return

	[ "$enabled" = "1" ] || return
	[ -n "$track_ip" ] || return

	procd_open_instance
	procd_set_param command /usr/sbin/mwan3track -i "$1" -m "$track_method" -r "$reliability" -c "$count" -t "$timeout" -v "$interval" -o "$down" -u "$up" $track_ip
	procd_set_param respawn 0 15 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load mwan3
	config_foreach start_instance interface
}

service_triggers() {
	procd_add_reload_trigger mwan3
}
