#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /etc/qos/sqm.conf
. ${SQM_LIB_DIR}/functions.sh
. ${SQM_LIB_DIR}/defaults.sh

[ -d "${SQM_QDISC_STATE_DIR}" ] || mkdir -p "${SQM_QDISC_STATE_DIR}"

for qdisc in $SQM_CHECK_QDISCS; do
	[ -f ${SQM_QDISC_STATE_DIR}/$qdisc ] && continue
	verify_qdisc $qdisc && touch ${SQM_QDISC_STATE_DIR}/$qdisc
done
