#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

[ "$OTB_TRACKER_STATUS" = "OK" ] && action="start" || action="stop"
[ -f "/var/run/sqm/$OTB_TRACKER_INTERFACE.state" ] && state="up" || state="down"

case "$action" in
	start)
		# If QOS is started, don't start twice
		[ "$state" = "up" ] && exit 0

		. /lib/functions.sh

		config_load network
		config_get trafficcontrol "$OTB_TRACKER_INTERFACE" trafficcontrol

		# Don't start if qos is off
		[ "$trafficcontrol" = "static" ] || exit 0
		;;
	stop)
		# If QOS is stopped, don't stop twice
		[ "$state" = "down" ] && exit 0
		;;
esac

/usr/lib/qos/run.sh "$action" "$OTB_TRACKER_INTERFACE"
