#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
START=60

_setup_qos() {
	# shellcheck disable=SC1091
	. /lib/overthebox

	trafficcontrol= ; config_get trafficcontrol "$1" trafficcontrol
	[ "$trafficcontrol" = static ] || return 0

	multipath= ; config_get multipath "$1" multipath
	case "$multipath" in
		master|on|backup|handover)
			ifname=   ; config_get ifname   "$1" ifname
			metric=   ; config_get metric   "$1" metric
			download= ; config_get download "$1" download
			upload=   ; config_get upload   "$1" upload
			#shellcheck disable=SC2016
			ubus call "network.interface.$1" status | jq -c \
				--arg ifname "$ifname" \
				--arg metric "$metric" \
				--arg download "$download" \
				--arg upload "$upload" \
				'{
					interface: $ifname,
					metric: $metric,
					wan_ip: .data.public_ip,
					downlink: $download,
					uplink: $upload,
				}' | otb_save_call_api PUT qos -d@-
			;;
	esac
}

start() {
	# shellcheck disable=SC1091
	. /lib/functions.sh

	config_load network
	config_foreach _setup_qos interface
}

restart() {
	start
}

reload() {
	start
}

stop() {
	/usr/lib/qos/run.sh stop

	# shellcheck disable=SC1091
	. /lib/overthebox

	echo | otb_save_call_api DELETE qos
}

service_triggers() {
	procd_add_reload_trigger network
}
