#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

start_instance() {
	procd_open_instance
	procd_set_param command /bin/graph "$@"
	procd_set_param respawn 15 30 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load graph
	config_foreach start_instance opentsdb
}

service_triggers() {
	procd_add_reload_trigger graph network
}
