#!/bin/sh

case "$ACTION" in
	ifup)
		logger mwan3 ifup $DEVICE

		MPTCP=$(uci -q get network.$DEVICE.multipath)
		case "$MPTCP" in
			"on");;
			"master")
				MPTCP="on";;
			"backup");;
			"handover");;
			*)
				MPTCP="";;
		esac

		if [ -n "$MPTCP" ]; then
			# Re-activate DNS of this interface
			sed -i "/# Interface $DEVICE/,/# Interface/ s/#nameserver /nameserver /" /tmp/resolv.conf
			sed -i "/# Interface $DEVICE/,/# Interface/ s/#nameserver /nameserver /" /tmp/resolv.conf.auto
			# static route for mptcp
			DST=$(uci -q get shadowsocks.proxy.server)
			GW=$(uci -q get network.$DEVICE.gateway)
			if [ -n "$DST" ] && [ -n "$GW" ]; then
				route add $DST gw $GW dev $DEVICE
				logger route add $DST gw $GW dev $DEVICE
			fi
			# Notify OverTheBox API
			/usr/bin/otb_notify_ifup $DEVICE &
			# On interface tracking back to life we re-initialize multipath on this interface
			/usr/bin/multipath $DEVICE off
			sleep 1
			/usr/bin/multipath $DEVICE $MPTCP
			sleep 5 # Workaround for full bandwidth issue
			/usr/bin/multipath $DEVICE off
			sleep 1
			/usr/bin/multipath $DEVICE $MPTCP

			logger /usr/bin/multipath $DEVICE $MPTCP
		fi
		;;
	ifdown)

		MPTCP=$(uci -q get network.$DEVICE.multipath)
		case "$MPTCP" in
			"on");;
			"master");;
			"backup");;
			"handover");;
			*)
				MPTCP="";;
		esac
		if [ -n "$MPTCP" ]; then
			# Desactivate DNS of this interface
			sed -i "/# Interface $DEVICE/,/# Interface/ s/nameserver /#nameserver /" /tmp/resolv.conf
			sed -i "/# Interface $DEVICE/,/# Interface/ s/nameserver /#nameserver /" /tmp/resolv.conf.auto
			# static route for mptcp
			DST=$(uci -q get shadowsocks.proxy.server)
			GW=$(uci -q get network.$DEVICE.gateway)
			if [ -n "$DST" ] && [ -n "$GW" ]; then
				route delete $DST gw $GW dev $DEVICE
				logger route delete $DST gw $GW dev $DEVICE
			fi
			# Notify OverTheBox API
			/usr/bin/otb_notify_ifdown $DEVICE &
		fi
		;;
esac

exit 0
