#!/bin/sh

[ "$ACTION" = "add" ] || exit 0
[ "$DRIVER" = "cdc_ether" ] || exit 0

log() {
    logger -t "hotplug-otb-cdc_ether" -p 6 "$*" || true
}

dev_path=$(find "/sys/${DEVPATH%/*}" -type d -name 'eth*')
dev_name=${dev_path##*/}
[ "$dev_name" ] || {
	log "Failed to find the network card for $DEVPATH"
	exit 1
}

if grep "$dev_name" /etc/config/network; then
	log "$dev_name already configured"
	exit 0
fi

# Get the first cifX available
_id=1
while uci -q get network.cif$_id >/dev/null; do _id=$((_id+1)); done

uci -q batch <<-EOF
set network.cif${_id}=interface
set network.cif${_id}.proto=dhcp
set network.cif${_id}.ifname=$dev_name
commit network

del_list firewall.wan.network=cif$_id
add_list firewall.wan.network=cif$_id
commit firewall
EOF

log "cif$_id ($dev_name) interface configured"
