#!/bin/bash
# We need to use bash for trap EXIT to work

IPT="iptables -w -t nat"
HOST="proof.ovh.net"
COMMENT="Test download proof"

# This function checks existence of an iptables chain
# $1 is the chain to test
_chain_exists() {
    $IPT -nL $1 &> /dev/null
    return $?
}

# This function is called if we get a SIGINT or SIGTERM
_cleanup() {
    $IPT -D socks_emitted_by_myself -d $HOST -j socks_redir -m comment --comment "$COMMENT"
    echo "Stopped"
}

if ! _chain_exists "socks_emitted_by_myself" || ! _chain_exists "socks_redir"; then
    echo "Couldn't find the iptables chain to plug myself into. Is ss-redir running?"
    return 1
fi

echo "Starting..."
$IPT -A socks_emitted_by_myself -d $HOST -j socks_redir -m comment --comment "$COMMENT"

# Note that trap EXIT works only because we use /bin/bash as shebang
trap _cleanup EXIT
wget http://$HOST/files/10Gio.dat -O /dev/null
