#!/bin/sh
# shellcheck disable=SC1091,SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

[ "$(uci -q get "glorytun.tun0")" = "mud" ] || exit 0

. /lib/functions/network.sh

_setup_multipath() {
	for iface in $(uci -q get firewall.wan.network); do
		case "$iface" in
			wan|tun0) continue ;;
		esac

		local ipaddr
		network_get_ipaddr ipaddr "$iface"
		[ "$ipaddr" ] || continue

		local table
		table="$(uci -q get "network.$iface.ip4table")"
		[ "$table" ] || continue

		case "$(uci -q get "network.$iface.multipath")" in
			on|up|'') glorytun path "$ipaddr" up     ;;
			backup)   glorytun path "$ipaddr" backup ;;
			*)        glorytun path "$ipaddr" down   ;;
		esac
	done
}

retry=3

while true; do
	if glorytun show 2>/dev/null | grep -sq client; then
		_setup_multipath
		exit
	fi
	if [ "$retry" == 0 ]; then
		logger -t "$0" "glorytun show failed"
		exit 1
	else
		retry=$((retry - 1))
		sleep 1
	fi
done
