#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
# shellcheck disable=SC2034

USE_PROCD=1

START=80
STOP=20

PROG="/bin/bandwidth"

start_service() {
	$PROG setup

	procd_open_instance
	procd_set_param command $PROG ipt-update
	procd_set_param respawn 0 300 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	$PROG unsetup
}

service_triggers() {
	procd_add_reload_trigger firewall
}
