#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

USE_PROCD=1
START=80
STOP=20

PROG="/usr/sbin/bandwidth"

start_service() {
	$PROG setup

	procd_open_instance
	procd_set_param command $PROG ipt-update
	procd_set_param respawn 300 300 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	$PROG unsetup
}
