#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

[ "$OTB_TRACKER_STATUS" = "OK" ] || exit

_curl() {
	curl --interface "$OTB_TRACKER_INTERFACE" --max-time 1 -Ss "$1"
}

pub_ip=$(_curl ifconfig.ovh)
asn=$(_curl api.iptoasn.com/v1/as/ip/"$pub_ip")
# shellcheck disable=SC2016
data=$(jq -n -c --argjson asn "$asn" --arg pub_ip "$pub_ip" '{asn:$asn, public_ip:$pub_ip}')
ubus call "network.interface.$OTB_TRACKER_INTERFACE" set_data "$data"
