#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

[ "$OTB_TRACKER_STATUS" = "OK" ] || exit

url_list="
	ifconfig.ovh
	ipaddr.ovh
"

_curl() {
	curl \
		--interface "$OTB_TRACKER_DEVICE" \
		--max-time "$OTB_TRACKER_TIMEOUT" \
		--silent \
		--show-error \
		"$1"
}

for url in $url_list; do
	pub_ip=$(_curl "$url" || true)
	[ "IP=$pub_ip" = "$(ipcalc.sh "$pub_ip" | grep IP)" ] && break
	pub_ip=
done
[ -z "$pub_ip" ] && exit 1

pub_ip_old=$(ubus call "network.interface.$OTB_TRACKER_INTERFACE" status | jq -r '.data.public_ip')
[ "$pub_ip" = "$pub_ip_old" ] && exit 0
# shellcheck disable=SC2016
data=$(jq -n -c --arg pub_ip "$pub_ip" '{public_ip:$pub_ip}')
ubus call "network.interface.$OTB_TRACKER_INTERFACE" set_data "$data"

asn=$(_curl api.iptoasn.com/v1/as/ip/"$pub_ip")
[ -z "$asn" ] && exit 1
# shellcheck disable=SC2016
data=$(jq -n -c --argjson asn "$asn" '{asn:$asn}')
ubus call "network.interface.$OTB_TRACKER_INTERFACE" set_data "$data"
