#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2016
data=$(jq -c -n --arg status "$OTB_TRACKER_STATUS" '{connectivity:$status}')
ubus call network.interface."$OTB_TRACKER_INTERFACE" set_data "$data"
