#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/functions.sh

multipath=
multipath_status=0
config_load network
config_get multipath globals multipath
[ "$multipath" = "enable" ] && multipath_status=1

# Global MPTCP configuration
sysctl -qw net.mptcp.mptcp_enabled="$multipath_status"
[ "$multipath_status" = "0" ] && exit 0

# Configuration by interface
_setup_interface() {
	device=
	config_get device "$1" device
	[ -z "$device" ] && return 0

	if_multipath=
	config_get if_multipath "$1" multipath "off"
	multipath "$device" "$if_multipath"
}
config_foreach _setup_interface interface
