#!/bin/sh
# shellcheck disable=1091
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

old_status=$(otb_get_data "$OTB_TRACKER_INTERFACE/connectivity")

[ "$old_status" = "$OTB_TRACKER_STATUS" ] && exit 0

logger -t "otb-tracker" "$OTB_TRACKER_INTERFACE tracking status changed to $OTB_TRACKER_STATUS"

otb_set_data "$OTB_TRACKER_INTERFACE/connectivity" "$OTB_TRACKER_STATUS"
