#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
START=90
STOP=10

USE_PROCD=1

validate_section() {
	uci_validate_section simpletracker track_interface "$1" \
		'method:string:dns' \
		'host:string:51.254.49.132' \
		'interface:string' \
		'timeout:integer:2'
}


start_track_interface() {
	validate_section "$1" || {
	echo "Cannot read uci configuration"
	return
}

procd_open_instance
procd_set_param command /usr/bin/track_interface.sh -m "$method" -d "tracker.overthebox.ovh" -t "$timeout" -h "$host" "$interface"
procd_set_param respawn  0 3 0
procd_set_param stdout 1
procd_set_param user root
procd_close_instance
}




start_service() {
	config_load simpletracker
	config_foreach start_track_interface track_interface
}
