#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# After mwan has potentially changed its conf, send the "config.change" event
# in case some services subscribed to it.
# Unfortunately, reload_config cannot take an argument :(
# We may potentially reload services who subscribed to reload_trigger other than "mwan3"
# But this is fine since reload_service only reload services for conf which really changed
reload_config
